export enum EnvKey {
  // App
  BASE_SERVER_URL = 'BASE_SERVER_URL',
  NODE_ENV = 'NODE_ENV',
  PORT = 'PORT',

  // Redis
  REDIS_URL = 'REDIS_URL',

  // MongoDB
  MONGO_URL = 'MONGO_URL',

  // HttpClient
  VLUTE_SSO_BASE_URL = 'VLUTE_SSO_BASE_URL',

  // Encryption
  MASTER_ENCRYPTION_KEY = 'MASTER_ENCRYPTION_KEY',

  // Cors
  CORS_ORIGIN = 'CORS_ORIGIN',

  // Google OAuth2
  GOOGLE_CLIENT_ID = 'GOOGLE_CLIENT_ID',
  GOOGLE_CLIENT_SECRET = 'GOOGLE_CLIENT_SECRET',
  GOOGLE_CALLBACK_PATH = 'GOOGLE_CALLBACK_PATH',
}
